### ISSUE TITLE
transaction_bytes_succ test is non-deterministic + failures based on key content

### ISSUE THREAD

**Issue by GwenNelson** [yobicash/libyobicash#5]
From time to time the test suite will fail on this test, giving the following output:

---- transaction::transaction_bytes_succ stdout ----
	thread 'transaction::transaction_bytes_succ' panicked at 'called `Result::unwrap()` on an `Err` value: YError(InvalidTime, State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906:4

This appears to be happening due to some property of some keys, hence why it passes some times and fails other times.

A verified permanent fix will require the following:

 1 - Identifying the property in the generated keys causing it to fail
 2 - Make the keys static, instead of dynamically generated at runtime, set the keys to known "bad" values
 3 - Fix the underlying implementation so that it no longer fails

Potentially similar issues could crop up elsewhere, but so far this is the only test i've seen that is failing in a non-deterministic manner despite the use of randomness in several locations in the test suite.

**Comment by chritchens** [comment]
It was a business logic error. The check function was checking if the transaction time was < the current time instead then in the future. Here is also an implicit issue that I've left for the future but that we should address: Bitcoin is giving +/- 2h as an acceptable range for timestamps. But it is super empirical. I do not have any experience with other protocols though. Time is definitely unreliable on the internet. In the wp a delta is set but not defined. So far it is 0. What about that?

**Comment by chritchens** [comment]
It should be fixed with commit 887fdf8b9a5e9edbfb248ae3e866010abc7c8a84, comment "Fix time check in transaction". An idea to avoid this kind of issues is to use property testing whenever needed. quickcheck.rs could help.
